FROM rockylinux:9

RUN dnf install -y net-snmp net-snmp-utils && \
    dnf clean all

# 설정 파일 복사
COPY conf/snmpd.conf /etc/snmp/snmpd.conf

# Trap 로그 디렉터리
RUN mkdir -p /var/log/snmptrapd

# snmpd(161) + snmptrapd(162) 동시 기동
CMD snmpd -f -Lo && snmptrapd -f -Lo -p /var/run/snmptrapd.pid
