# ---- R1 (Loopback0 기준) ----
client R1 {
    ipaddr    = 10.10.10.1
    secret    = team2
    shortname = R1
}

# ---- R2 (Loopback0 기준) ----
client R2 {
    ipaddr    = 10.10.30.1
    secret    = team2
    shortname = R2
}

# ---- R1 인터페이스 IP (소스 고정 미적용 시 fallback) ----
client R1-if {
    ipaddr    = 172.16.10.1 
    secret    = team2
    shortname = R1-if
}

# ---- R2 인터페이스 IP (소스 고정 미적용 시 fallback) ----
client R2-if {
    ipaddr    = 192.168.0.11
    secret    = team2
    shortname = R2-if
}
